### ISSUE TITLE
The top of the head looks like it's been cut off.

### ISSUE THREAD

**Issue by waittingsummer** [kostoskistefan/hoverclock#1]
![image](https://github.com/kostoskistefan/hoverclock/assets/32017265/57d0433d-45ef-4230-9431-c518d0b5db14)
from deepinV23

**Comment by kostoskistefan** [comment]
Hello!

Please provide the contents of your `hoverclock.vault` configuration file, so I can do some testing and report back to you with a possible solution.

**Comment by waittingsummer** [comment]
Where is the `hoverclock.vault` ? Only these sreenshots.
![截图_AppRun wrapped_20231228200852](https://github.com/kostoskistefan/hoverclock/assets/32017265/e7637010-0433-477c-90d6-d7b3ae688d4e)
![截图_AppRun wrapped_20231228200855](https://github.com/kostoskistefan/hoverclock/assets/32017265/fd248ff4-5fa1-4b9c-aaaf-6965127045d3)
![截图_AppRun wrapped_20231228200859](https://github.com/kostoskistefan/hoverclock/assets/32017265/6d8c3bbf-49f4-4eea-8b98-d97982efe6fc)

**Comment by kostoskistefan** [comment]
Ah okay. This makes a lot of sense now. 

The application that you currently have installed is the QT version of Hoverclock, which was transfered to a different repository: [Hoverclock-QT](https://github.com/kostoskistefan/hoverclock-qt). Active development of that version has stopped in favour of the new, much more optimized and lightweight version located in [this repository](https://github.com/kostoskistefan/hoverclock/). Even though some of the features that the QT version has are yet to be implemented, it is recommended to switch to this version if you can.

One difference between the QT version and the version in this repository, besides the massive optmizations, is mainly in the way they are configured. The QT version has the configuration dialog of which you posted images, whilst the new version of Hoverclock is configured through a file called `hoverclock.vault`. It supports most of the features that the QT version has and it is very easy to configure. You can find all of the instructions in the README file of this repository.

Also, I can see that you are currently using version 0.0.1, which is quite old. If you still prefer to use the QT version, you can download the latest version (v1.0.0) here: [https://github.com/kostoskistefan/hoverclock-qt/releases/tag/v1.0.0](https://github.com/kostoskistefan/hoverclock-qt/releases/tag/v1.0.0).

I hope this helps. If you need any further assistance, don't hesitate to ask!

**Comment by waittingsummer** [comment]
Ah okay. Have a nice day!

**Comment by aksh1618** [comment]
> which was transfered to a different repository: [Hoverclock-QT](https://github.com/kostoskistefan/hoverclock-qt).

Hey @kostoskistefan, quick side note: the transfer seems to have broken the [AUR package](https://aur.archlinux.org/packages/hoverclock-bin).

(PS: Thanks for making this simple yet priceless utility!)
(PPS: Would love an AUR package for this optimized version!)

**Comment by kostoskistefan** [comment]
> Hey @kostoskistefan, quick side note: the transfer seems to have broken the [AUR package](https://aur.archlinux.org/packages/hoverclock-bin).
> 
> (PS: Thanks for making this simple yet priceless utility!) 
> (PPS: Would love an AUR package for this optimized version!)

You are absolutely right! Thanks for noticing and reporting the issue. I'll fix it soon and I'll make an AUR package for this version as well. 

Thanks for the suggestion and I'm really glad you enjoy using Hoverclock and find it useful!
